# Generated by Django 6.0.4 on 2026-05-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alert_is_read_subscription_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='charge',
            options={'ordering': ['-charge_date']},
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.UniqueConstraint(fields=('subscription', 'amount', 'charge_date'), name='unique_charge_per_subscription_day'),
        ),
    ]
